export default {
  UPDATE_PRODUCT_ON_SHELF: 'UPDATE_PRODUCT_ON_SHELF',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',

  UPDATE_CART_QUANTITY: 'UPDATE_QUANTITY',

  UPDATE_ORDERS: 'UPDATE_ORDERS',
  UPDATE_PENDING_ORDERS: 'UPDATE_PENDING_ORDERS',
  UPDATE_COMPLETED_ORDERS: 'UPDATE_COMPLETED_ORDERS',
  UPDATE_INCOME_DATA: 'UPDATE_INCOME_DATA',

  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
};
